### ISSUE TITLE
Reported segfault

### ISSUE THREAD

**Issue by benkohler** [Synss/elogviewer#10]
On our last stabilization of ~3.0 on gentoo, one of our developers saw a segfault and applied a patch:

https://bugs.gentoo.org/721522#c2

Can you verify this is correct and add that to the official release so we don't have to keep carrying that patch?

Thanks!

**Comment by Synss** [comment]
Hi! Sure! I'll have a look.

**Comment by Synss** [comment]
I have made a different patch that should solve the issue as well. I will make a v3.2 when the CI is green.

**Comment by Synss** [comment]
done https://github.com/Synss/elogviewer/archive/v3.2.tar.gz

Funny I did not get the discussion on bugzie. I will have to check that. Thank you for reporting here!
