### ISSUE TITLE
Change config directory name to 'elogviewer'

### ISSUE THREAD

**Issue by fonic** [Synss/elogviewer#3]
I'd like to recommend changing the config directory name from _Mathias Laurin_ to _elogviewer_. On Linux, it is common practice for the config directory name to reflect the application it belongs to.

Since changing this will invalidate existing configurations for users upgrading elogviewer, I think it would be a good idea to have the ebuild announce the change, e.g.

```
* Please note that the configuration directory changed from
* '~/.config/Mathias Laurin/' to '~/.config/elogviewer/'. If
* you're upgrading and like to keep your previous settings,
* please rename the directory accordingly.
```

**Comment by Synss** [comment]
Sure, that is a good idea 👍. Actually, I have my name there because the field in `QSetting` is called `organization` and I did not really know what to put there. `elogviewer` is a much better idea. Feel free to send a pull request if you like.

**Comment by fonic** [comment]
Created pull request #4 for the change, therefore closing this issue.
