### ISSUE TITLE
Marking entries as read/unread is inconsistent

### ISSUE THREAD

**Issue by fonic** [Synss/elogviewer#6]
I noticed the following inconsistencies:
- marking an already read entry as unread using Space key with focus on green bullet doesn't restore the bold font of the row
- marking read/unread by clicking on green bullet doesn't work

Edit:
A dark star turns red when clicking it, but when leaving + restarting elogviewer, it is dark again. Probably a related issue?

**Comment by Synss** [comment]
Sorry for the late answer. Apparently the `ReadFontStyleDelegate` is not informed of the change. I am not sure how to fix this.

**Comment by Synss** [comment]
I think I have got it in f48c2970e0093681762744164a1b4aa4d046a8aa.

I just need to double check and merge the patch. Thank you for reporting the issue.

**Comment by Synss** [comment]
f48c2970e0093681762744164a1b4aa4d046a8aa

**Comment by Synss** [comment]
I will merge this later as this resulted in another UI bug. I am working on it.
