### ISSUE TITLE
Deprecation warnings with python3.8

### ISSUE THREAD

**Issue by benkohler** [Synss/elogviewer#9]
Hi,

I just bumped the ebuild in ::gentoo repo for 3.0 and I added python3_7 & python3_8 support on it... it runs on 3.8 but emits a warning, this is probably something that should be fixed before 3.9 gets here.  Thanks!

$ elogviewer
/usr/lib/python-exec/python3.8/elogviewer:689: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.resize(screenSize.width() / 2, screenSize.height() / 2)

**Comment by Synss** [comment]
Thank you!

That looks easy enough. I'll fix it shortly.

Cheers,
Mathias

**Comment by Synss** [comment]
I have fixed the warnings now and released a [v3.1](https://github.com/Synss/elogviewer/releases/tag/v3.1).

Thank you for reporting the warnings and packaging!
